### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by nickyhajal** [greatenemy/svelte-ace-editor#4]
Hi there, I'm trying to use this package running on a Sapper project and receiving the following error. Any ideas how to get it running?

```
500

window is not defined

ReferenceError: window is not defined
    at /Users/nicky/Sync/Work/multitool/node_modules/brace/index.js:20265:21
    at _acequire (/Users/nicky/Sync/Work/multitool/node_modules/brace/index.js:88:37)
    at Object.acequire (/Users/nicky/Sync/Work/multitool/node_modules/brace/index.js:93:26)
    at /Users/nicky/Sync/Work/multitool/node_modules/brace/index.js:20260:21
    at Object.<anonymous> (/Users/nicky/Sync/Work/multitool/node_modules/brace/index.js:20270:15)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
```

**Comment by carcinocron** [comment]
https://github.com/greatenemy/textsort-sapper and https://github.com/greatenemy/sql-sapper are both working examples.

I barely remember, but this is a weird thing with svelte/sapper and the dev server's "always on SSR" (I don't fully understand it) -- but I think I worked around it by wrapping some of the requires with `if (process.browser) { require(...) }`

example:
https://github.com/greatenemy/textsort-sapper/blob/master/src/components/TextSort.svelte#L82
https://github.com/greatenemy/sql-sapper/blob/master/src/components/SqlPrettifier.svelte#L92

The `brace` library itself is what requires `window`.

If it's not that, I'd need to see more code.
